---
title: "Solutions for exercise set 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r eval=FALSE}
## 2.1 more data structures

# Q.2.1.1 
# I am using a:b, sample(), and c() to create my vectors
# you could also use any number of other functions, like seq(), runif() etc
x <- 5:8
y <- sample(10:100, 4)
z <- c(1, 26, 3, 88)

# Q2.1.2
# joining vectors to a matrix and assigning the result into a variable
mat <- cbind(x,y,z)

# Q2.1.3
# in 2-D structures, indexing goes row, vector
# this will also print the name of the vector the value came from
print(mat[2,3])

# Q2.1.4
# you can do this all in one line like so
mat2 <- matrix(runif(9), nrow=3, ncol=3)

# but an equally valid method would be to first create the numbers
randnumbers <- runif(9)
# and then make the vector into a matrix
other_mat2 <- matrix(randnumbers, nrow=3)

# Q2.1.5
# you can use vectors in square bracket indexing to get results which are matrices (or vectors), not just single numbers
print(mat2[2:3,2:3])

# Q2.1.6
thisisalist <- list(mat, mat2)

# Q2.1.7
# keep in mind the double bracket indexing for lists
# the [[1]] is to get to the correct element in the list, the [1,1] is to get the correct element of the matrix inside the list
thisisalist[[1]][1,1] 

## 2.2 Working with data

# Q2.2.2
data <- read.csv('/Users/juusu53/Documents/projects/opetus/R_for_scientists/R_at_CSAN/exercise_data.csv')

# Q2.2.3
head(data)

# Q2.2.4 
# you can change the number of values you want printed with the argument n
tail(data, n=10)

# Q2.2.5
summary(data)

# Q2.2.6
library(psych)
# NB: in a typical script file you should have the packages at the very top so that a reader knows what is required to run the script! I have the package defined here to show that this
# is the part of the exercises when you come across the need for this package, but if this was a script I wrote for myself, the packages would all be at the very top
describe(data)

# Q2.2.7 
data[7,]

# Q2.2.8 
data$sex

# Q2.2.9
# row 7 has a lot of missing values (NA)
# we can easily check the number of missing values in a matrix or vector with is.na and sum like so 
sum(is.na(data[7,]))
# since truth values are also 0 (FALSE) and 1 (TRUE). If we wanted to check how many values are not NA, we could do
sum(!is.na(data[7,]))

# sex is shown as numeric, although we know that logically it is a categorical variable

# Q2.2.10
data$sex <- factor(data$sex, levels=c(1,2), labels=c('female','male'))
data$education <- factor(data$education, levels=c(1,2,3,4), labels=c('primary', 'secondary', 'vocational', 'university'))

# Q2.2.11
summary(data)
# the columns that were made into factors are now showing counts of each factor level instead of mean etc

# Q2.2.12
data[,c('age','sex', 'education', 'curr_pain_extent')]

# Q2.2.13
# select only male subjects
data[data$sex == "male",]
# select male subjects aged 30 and up
data[data$sex == "male" & data$age >=30,]
# notice that now the comma is after the logical operators, since our logical operators are choosing rows (not columns as in Q2.2.12)

# Q2.2.14
# The plots look different, because one has continuous variable as the x axis and the other one has a categorical variable. Therefore,
# R assumes you want different kinds of plots by default

# Q2.2.15-Q.2.2.20
pdf('/Users/juusu53/Documents/projects/opetus/R_for_scientists/course_materials/data/sample_plot_1.pdf')
hist(data$age, breaks=50, xlab="Age of participants", ylab="Number of participants", main="Age distribution of participants",
     col='grey')
dev.off()

# Q2.2.21
# the code plots two data series together on the same axis
# Add=T tells the figure to keep the old plot 
# Freq toggles between frequency (how many observations) and probability density. 
# This is particularly relevant to use if your samples are very different in size, like in this case where there are many, many more female participants than male participants

# Q2.2.22
with(data, plot(age, weight, 
                pch = 19, col=c('cyan','royalblue2','blue','darkblue')[as.integer(education)],
                xlab = 'age',
                ylab = 'weight',
                main='Age vs weight'))

## 2.3 Conditional statements

# Q2.3.2
# Below, we only loop over the first 20 rows of data. If you wanted to go over the whole data set, you would say for(row in 1:nrow(data)) instead
for(row in 1:20){ 
  if (is.na(data$work_physical[row])){
    cat(paste0("We do not know if subject ", data$subid[row], " does physically demanding work.\n"))
  } else if (data$work_physical[row] <= data$work_sitting[row]){
    cat(paste0("Subject ", data$subid[row], " does more sitting work than physically demanding work.\n"))
  } else {
    cat(paste0("Subject ", data$subid[row], " does more physically demanding work than sitting work.\n"))
  }
}

# Q2.3.3
for(row in 1:nrow(data)){
  cat(paste0("This is subject number ", data$subid[row], '.\n'))
}

# Q2.3.4

for(row in 1:nrow(data)){
  if (data$sex[row]=='female'){
    pronoun = 'She'
  } else {
    pronoun = 'He'
  }
  cat(paste0("This is subject number ", data$subid[row], '. ', pronoun, ' is ', data$age[row], ' years old.\n'))
}

# The loop above only operates with two sexes (male, female). This is due to the fact that the data set we're working on only has male and female participants on it. If you have a data set with either missing gender values (NA) or provide the option "rather not say", "other" or similar, you might want to use something like the loop below which also uses the 'they' pronoun. For if-else statements, you should always start with handling special cases so that they get captured correctly

for(row in 1:nrow(data)){
  if (is.na(data$sex[row])){
    pronoun = 'They are '
  } else if (data$sex[row]=='female'){
    pronoun = 'She is '
  } else {
    pronoun = 'He is '
  }
  cat(paste0("This is subject number ", data$subid[row], '. ', pronoun, data$age[row], ' years old.\n'))
}

```
