---
title: "Solutions for exercise set 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r eval=FALSE}
library(tidyverse)
library(patchwork)

setwd('/Users/juusu53/Documents/projects/opetus/R_for_scientists/R_at_CSAN/data/')
## 3.1 Tidy data 
# Q3.1.1
data <- read_csv('/Users/juusu53/Documents/projects/opetus/R_for_scientists/R_at_CSAN/data/exercise_data_not_tidy.csv')
# inspect the tibble
data

## wrangling the data
# Q3.1.2 
# I would argue that in this case, it makes most sense to have the self-reported emotions eachin their own column like they were in the last set of exercises. We also have a second data file which we need to join to the first one.

# Q3.1.3
# we can use the function spread (from tidyr) to go from long to wide
data <- data %>% spread(key='emotion', value='self_report')
# or using pivot_wider in newer versions of tidyverse
data <- data %>% pivot_wider(names_from='emotion', values_from='self_report')

# adding in the second data file
# first read in data
data_add_in <- read_csv('/Users/juusu53/Documents/projects/opetus/R_for_scientists/R_at_CSAN/data/exercise_data_not_tidy_add_in.csv')
# the column by which we match the data is called "subid" in both data.frames, so we can just say
data <- full_join(data, data_add_in)
# inspect to make sure the join worked
View(data)

## cleaning and manipulating the data
# Q3.1.4 
summary(data)
plot(data$height)
plot(data$weight)
plot(data$age)
# looks like we have a few problems: there are some subjects with weight and height either negative or around zero - that cannot be true
# we have one subject whose age is 99. We can't be sure if that is correct, but let us assume that that's also mistake and replace that with NA

# Q3.1.5

# we can use mutate and na_if to deal with the badly coded NAs
data <- data %>% mutate(height = na_if(height, -1), 
                        weight = na_if(weight, -99),
                        age = ifelse(age > 85, NA, age))

# Q3.1.6
# looks like sex and education should both be factors, let's take care of that
# the categories are the same as last time
data <- data %>% mutate(sex = factor(sex, levels = c(1,2),labels=c('female','male')), 
                        education = factor(education, levels=c(1,2,3,4), 
                                           labels=c('primary','secondary','vocational', 'university')))

# Q3.1.7
# let's shorten the names of the unnecessarily long columns with rename
data <- data %>% rename(work_physical = percentage_work_time_physical, 
                        work_sitting = percentage_work_time_sitting,
                        pain = current_feeling_pain,
                        depression = self_assessed_depression,
                        anxiety = self_assessed_anxiety)

# Q3.1.8
# Let's make a column for BMI
data <- data %>% mutate(BMI = (weight / (0.01*height)^2 )) 
# Note: we're using 0.01*height because the formula requires height in meters and our data has it in centimeters

# Q3.1.9 
counted_data <- data %>% group_by(sex, education) %>% tally()

## Note: Above, I have split up the different steps of this process for pedagogical reasons. If you wanted, you could do the same data cleaning in a much more condensed format, like so: 
data <- read_csv('/Users/juusu53/Documents/projects/opetus/R_for_scientists/R_at_CSAN/data/exercise_data_not_tidy.csv')
data_add_in <- read_csv('/Users/juusu53/Documents/projects/opetus/R_for_scientists/R_at_CSAN/data/exercise_data_not_tidy_add_in.csv')

data <- data %>% pivot_wider(names_from='emotion', values_from='self_report') %>% 
  full_join(data_add_in) %>% 
  mutate(height = na_if(height, -1), 
                        weight = na_if(weight, -99),
                        age = ifelse(age > 85, NA, age)) %>% 
  mutate(sex = factor(sex, levels = c(1,2),labels=c('female','male')), 
                        education = factor(education, levels=c(1,2,3,4), 
                                           labels=c('primary','secondary','vocational', 'university'))) %>% 
  rename(work_physical = percentage_work_time_physical, 
                        work_sitting = percentage_work_time_sitting,
                        pain = current_feeling_pain,
                        depression = self_assessed_depression,
                        anxiety = self_assessed_anxiety) %>% 
  mutate(BMI = (weight / (0.01*height)^2 ))
## (you would still want to build your process step by step, making sure outcome after each step is what you want it to be)

# Q3.1.10
for(column in colnames(data)){
  print(paste(column, 'has', sum(is.na(data[,column])), 'NAs'))
}
# of course an easier way to get the same information would be to get a summary of the data set
summary(data)

## 3.2 ggplot2 + patchwork

# Q3.2.1 
ggplot(data, aes(age)) +
  geom_histogram()

# Q3.2.2
# aes refers to aesthetics, ggplot's way of defining how to map data onto the plot
# if you skip the +, the latter lines won't be understood as part of the same plot call

# Q3.2.3 
ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram()

# Q3.2.4
ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram(position='identity')

# Q3.2.5 
ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram(position='identity', alpha=0.5)
# larger numbers for alpha make the colours more solid, smaller numbers make it more see-through

# Q3.2.6
ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram(position='identity', alpha=0.5, aes(y=..density..))

# Q3.2.7
ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram(position='identity', alpha=0.5, aes(y=..density..)) +
labs(title="Age distribution", x="Age", y = "Density")

# Q3.2.8
ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram(position='identity', alpha=0.5, aes(y=..density..)) +
labs(title="Age distribution", x="Age", y = "Density") +
  theme_classic()

# Q3.2.9

ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram(position='identity', alpha=0.5, aes(y=..density..)) +
labs(title="Age distribution", x="Age", y = "Density") +
  geom_density(alpha=0.2) +
  stat_function(fun = dnorm, n = 101, args = list(mean = mean(data$age, na.rm=T), sd = sd(data$age, na.rm=T)), colour='red') + 
  theme_classic(base_size=20) +
  theme(legend.position = 'bottom')

# Q3.2.10
p1 <- ggplot(data, aes(x=age, fill=sex)) +
  geom_histogram(position='identity', alpha=0.5, aes(y=..density..)) +
labs(title="Age distribution", x="Age", y = "Density") +
  geom_density(alpha=0.2) +
  stat_function(fun = dnorm, n = 101, args = list(mean = mean(data$age, na.rm=T), sd = sd(data$age, na.rm=T)), colour='red') + 
  theme_classic(base_size=20) +
  theme(legend.position = 'bottom')

pdf('/Users/juusu53/Documents/projects/opetus/R_for_scientists/R_at_CSAN/age_distribution.pdf')
p1
dev.off()

# Q3.2.11
# let's see if the self-reported happiness/joy is associated with
# how depressed the subject is feeling
# both were collected on a scale from 0 to 10 - not exactly a continuous scale but we can still use scatter plot to look at it as long as we use geom_jitter to add a bit of visual jitter 
ggplot(data, aes(x=depression, y=joy)) + 
  geom_jitter()

# Q3.2.12
# looks like higher depression is associated with lower levels of joy - who would've thunk!
ggplot(data, aes(x=depression, y=joy)) + 
  geom_jitter() + 
  geom_smooth(method='lm')

# Q3.2.13
# for this plot, I've decided to take out the confidence estimates for the trend line (se=F), and added sex information to the dot color. Notice how having dot color defined by sex gives us separate trend lines for males and females?
p2 <- ggplot(data, aes(x=depression, y=joy, col=sex)) + 
  geom_jitter(alpha=0.5) +
  geom_smooth(method='lm', se=F, size=2) + 
  labs(title = 'Depression suppresses joy', xlab='Depression', ylab='Happiness') +
  theme_classic() +
  theme(legend.position = 'bottom',
        text = element_text(size=16))

# Q3.2.16
p1 + p2

# Q3.2.17
p1 / p2

# Q 3.2.18
# for this purpose, maybe the one row, two column thing worked better?
# You can also use patchwork to build more complex layouts, like
p1 + p2/p2
p1 / (p2 + p2)

```
